### ISSUE TITLE
Pattern Error reported by GandalfTheWhit 

### ISSUE THREAD

**Issue by mikebryant** [mikebryant/ac-nh-turnip-prices#118]
Moving https://github.com/mikebryant/ac-nh-turnip-prices/issues/114#issuecomment-614176535

@GandalfTheWhit Thanks for reporting, but I need to keep this stuff in separate threads or I can't handle it. I've moved your comment here

> I've been tracking a few people's turnip prices, and have encountered some similar issues. I've got one person who is a first time buyer, only person on their island, and these are their prices starting with sunday thru to today.
94 | 122 | 140 | 151 | 124 | 148 | 57

> It breaks the second I put that 124 value in. No time travel. I'm just getting here but my best guess at this point is something to do with the first time buyer boolean. I also had a similar issue for an island where the first time buyer was a resident, not the owner. Trying to find those numbers.

**Comment by GandalfTheWhit** [comment]
Sorry, new to github. Thanks.

**Comment by mikebryant** [comment]
No problem :)

As a first time buyer, these would be the small spike pattern

That pattern has a sequence of days:
(define X as somewhere between 1.4 to 2.0)
- 0..9* to 1.4*
- 0..9* to 1.4*
- 1.4* to X*
- X*
- 1.4* to X*

with everything on either side being a decreasing phase.

This is possible with the data provided, except for the 124 - that should be the spike, and instead it's too low - and it would *have* to be bigger than the ones either side, i.e. 148 & 151

I just don't see how these data would fit into any of our patterns, the tool can't cope with this.

Are you confident the 124 price is accurate?

I don't think we're going to be able to do anything to make the tool support this case.

**Comment by GandalfTheWhit** [comment]
It's second hand reporting so I'm as confident as I can be in the person reporting. Again, I need to find my numbers from the other first time buyer that didn't fit any of the patterns. I seem to remember the pattern being similar to the issue with the 124. I was thinking this might be some weird fifth pattern that only occurs for first time buyers?

**Comment by GandalfTheWhit** [comment]
Sorry here they are. These were my numbers, first time buying (me/anyone on the island), no time travel, I am a resident on the island, not the owner. 

Sunday: 90  
48, 44, 147, 98, 181, 195

**Comment by mikebryant** [comment]
We have been making various tweaks over the last week

**Comment by theRTC204** [comment]
_takes a really deep breath.... "hold my beer"_

> I was thinking this might be some weird fifth pattern that only occurs for first time buyers?

I can assure you there is no fifth pattern that it could be assigning. The game code is quite clear in that regard. When it's the first time buying, the pattern is set to 3.

> 94 | 122 | 140 | 151 | 124 | 148 | 57

So pattern 3 has three phases... decreasing, spike, decreasing.

**The first phase (decreasing)** can be anywhere from 0 to 7 periods, with each period guaranteed to be lower than the previous. Given your Monday AM price was higher than your buy price, we can deduce that you lucked out and skipped the first phase entirely.

**The second phase (spike)** is exactly 5 periods long. The first two periods are calculated with `randfloat(0.9, 1.4) * basePrice`, so they could fluctuate up or down a bit. In your case, you were lucky again and landed two increases back to back here (122 then 140). The remaining periods in this phase are the actual spike...
```cpp
rate = randfloat(1.4, 2.0);
sellPrices[work++] = intceil(randfloat(1.4, rate) * basePrice) - 1;
sellPrices[work++] = intceil(rate * basePrice);
sellPrices[work++] = intceil(randfloat(1.4, rate) * basePrice) - 1;
```
For the third period in this phase, the effective rate is `intceil(randfloat(1.4, rate) * basePrice) - 1`, but the probability of hitting the higher range is reduced by two calls to `randfloat()`, where the second call's high end range is the result of the first call. In your case you came out with a 151 here.

The fourth period in this phase is calculated with `intceil(rate * basePrice)` where `rate` is the previously stored value that was used to add some salt to the last period's range. Notice the abscence of the subtract 1 as well. This is where your numbers break down - the algorithm indicates that a value of 124 is impossible for two reasons.

The first reason being the lowest possible rate here is 1.4, and `94 * 1.4 = 131.6`, and when passed into `intceil()` we end up with...
```
94 * 1.4 = 131.6
131.6 + 0.99999 = 132.59999
132.59999 = (int) 132
```
The second reason is clear without needing to breakdown the math here, simply because period three ends with a subtract 1, we know without a doubt that period four will be higher.. Since we know you got a 151, then we can deduce you actually RNG'd a 152 in this period, making that the lowest possible value for perioud four.

The fifth and final period in this phase is another `intceil(randfloat(1.4, rate) * basePrice) - 1`.

**The third phase (decreasing)** makes up the remainder of the 12 total phases, based on however many are left given how many occurred in the first phase. Every period in this phase will be at the absolute best `0.9` of the previous period.

**Comment by mikebryant** [comment]
Since the set of your own numbers is currently being handled correctly, and the ones that don't work are second-hand, I'm going to close this issue. I don't think there's anything we can do here.

Thanks for raising this, and I hope the site continues to work well for you! :)

**Comment by GandalfTheWhit** [comment]
@theRTC204 Thanks for the detailed response! I'll try to get some more data and let you all know if this pops up again. I also haven't had a chance to look at the code yet but I intend to.

**Comment by theRTC204** [comment]
No problem! Happy to help were I can!
