### ISSUE TITLE
Copy issue on mobile devices

### ISSUE THREAD

**Issue by DICE2O** [mikebryant/ac-nh-turnip-prices#156]
The commit f67b014 use an input to copy permalink but it will let the keyboard on mobile devices pop up when click the copy button.
I think using clipboard.js is a better way to copy permalink.

**Comment by theRTC204** [comment]
Can you please provide examples where this is the case?

Device, OS version, browser & browser version if you can.

I do not get a keyboard on Android 10 in browser or PWA form.

**Comment by DICE2O** [comment]
Device: iPhone & iPad
OS Version:  iOS 13.4.5/ iPadOS 13.4
Browser: Safari / Chrome on iOS
Both PWA and browser have this problem.

**Comment by theRTC204** [comment]
Just read through the implementation of clipboard.js, and they are using almost an identical approach as ours, except that we have a hidden input that exists all the time, while they only add one for the duration of the copy.

As far as the keyboard remaining open, I've been able to reproduce that on an iPhone. The cause seems to be simply not dropping focus from the input after completing the copy command.

I will put up a PR for this in the morning.

Thanks for raising this @DICE2O!
