### ISSUE TITLE
New price outside of predicted range

### ISSUE THREAD

**Issue by Varijon** [mikebryant/ac-nh-turnip-prices#157]
To my surprise, the price (198) I received Friday AM doesn't fit in the calculations and breaks the pattern.
[Prices](https://turnipprophet.io?prices=93.80.76.70.67.62.57.119.102.198...&pattern=0)

According to the pattern, I was going to get a price between 130 and 185, then guaranteed higher roll at PM. Now I'm totally not sure if I should sell, might it be a large spike pattern after all? .. or still go higher like predicted.

**Comment by peter50216** [comment]
Is this the first week you've bought turnips on your island? Checking the "First-Time Buyer" checkbox does give me some prediction.

**Comment by Varijon** [comment]
Interesting how that makes it work.. but no, this is the third time. I'm very confident in my prices as I meticulously keep track of them in a spreadsheet as I get them. Also have last week's prices if they're needed for something.

**Comment by theRTC204** [comment]
Yea, your numbers are perfectly possible if it's the first time you buy turnips on your own island. This is because the game regenerates your prices on the day after your first time purchasing on your own island.

This effectively makes your buy price for that week irrelevant, and also hidden from you. Based on your numbers, we can predict that the hidden buy price is somewhere between 97-110, but more likely to be on the higher end of that.

It also means that your Friday PM is likely to increase again! :)
