### ISSUE TITLE
Can we have a Discord server to collab on this project?

### ISSUE THREAD

**Issue by Trevor-Welch** [mikebryant/ac-nh-turnip-prices#17]
There are a few people who have shown interest in wanting to help out on different parts of the code.

I'd love to see this app flourish and become more widely used in the AC community, so I'd love to help this grow.

**Comment by mikebryant** [comment]
Discord isn't something I've done much with - but sure :)

https://discord.gg/bRh74X8

**Comment by theRTC204** [comment]
We should consider adding the Discord invite to the README. I would suggest the website, however the Discord is more for development related discussion at the moment, and a link on the website would encourage those who are strictly users to join in.

**Comment by Lysoun** [comment]
Right now, the Discord needs to be more organised if we are to welcome a lot of people, including users. I suggest different roles: 

- (?) Discord moderators: since the main development team may not be interested in moderating the Discord server a lot, these people could be the ones to do it. They have access to everything on the Discord and are responsible for its organisation. They also should be careful about respect questions between users in the server, which certainly won't be a problem but if there were people to take care of that, that would be them.

- Main developers of the project: those developers are the ones reviewing pull requests and they have a vision for turnip prophet future. They are the experts here and could answer questions from people who would like to contribute but do not understand very well the code. They have access to a dedicated channel only for them to talk about the scope or stuff like that. Not sure if this role really is necessary, you tell me.

- Other contributors: people who would like to contribute or already did. They have access to a development channel where they could ask code-related questions.

- Users: those are our dear users, who might have suggestions or questions about the turnip prophet app. They only have access to channels dedicated to suggestions, questions and a general one for discussions that may not enter in one of those categories

With those roles come channels that people may (or not) have access to, here is a list of what I could think of: 

- general (everyone): for general discussion, not related to the turnip prophet app
- troubleshooting (everyone): when users have problems with the app, they can report their problems here. 
- suggestions (everyone): for suggestions about the application. Suggestions that seem to be interesting could lead to issues on the github repository. There may be a way to vote for suggestions that you like, like putting a 👍 on a suggestion. That system could help the development team to see which features are most asked for. 
- development (all developers): development-related discussions like people announcing on what they are going to work (to avoid multiple people working on the same subject at the same time), talking refactoring... 
- development-troubleshooting (all developers): for developers that are trying the develop something but everything is not going like they would like to and they need help

**Comment by Lysoun** [comment]
Having a Discord open to users too will certainly help us have more feedback on the app usage. Since many users of the turnip prophet are not developers, there may be some things that we are missing. 

Still I think it would help to organise more the Discord server. I have seen interesting discussions about issues there and, as we are talking on the server, those will be difficult to find with time and not be helpful for some contributor that was not present at that time.
