### ISSUE TITLE
Collapse all fluctuating pattern variations into a single row

### ISSUE THREAD

**Issue by doopl** [mikebryant/ac-nh-turnip-prices#187]
Near the beginning of the week they add a lot of noise to the table. I think most people would get more useful information from a single row than from screens full of possible variations at minute probabilities.

Here are some exceptions where it may still be worthwhile listing all the variations:
- If the user has opted-in to seeing them through some UI element.
- If every other pattern is ruled out.
- If there would be few (<12?) rows in the table anyway.
- If a price near the end of the week has been entered. (With limited opportunities left to sell it could be useful to provide more information to the user.)

I suppose the ideal implementation would be to have every pattern type expandable/collapsible dynamically, with the fluctuating pattern collapsed by default.

**Comment by theRTC204** [comment]
I can definitely understand the value in removing clutter from the UI, but this proposal, at least as it's documented, seems like it would introduce quite a bit of complexity to both the app code and the user experience.

There may be a way to refine the proposal and make it simpler overall. Perhaps a single toggle that can hide predictions below a preset probability, as opposed to collapsing specific patterns.

We already see a substantial number of issue reports from users unable to find matching patterns where the reason can be attributed to confusion around how to use the app. We have work to do already to simplify things, so I am hesitant to add functionality that adds complexity.

#my2cents

**Comment by doopl** [comment]
Thank you for your reply! I understand the concerns about complexity. Allow me to present the simplest version of this request:

- The fluctuating pattern variations are aggregated on to one row. Individual variations are hidden and there is no option to display them.

Considering there is already an "All patterns" row in the table which aggregates every variation of every pattern it doesn't seem like it would take much additional code to do the same but only for the variations of a single pattern.

I added the caveats to the issue originally because I anticipated someone being unhappy that information would be hidden and I wanted to account for that. Personally I don't need or particularly care about any of those things.

Just to explain my reason for this proposal - I want to recommend this price tracker to my friends because, out of the various options available, this one seems the best at providing accurate probabilities of being on each pattern. However I am reluctant to do so because I expect them to see this and wonder WTF they are looking at:

![image](https://user-images.githubusercontent.com/1728488/79692297-353cca80-825c-11ea-9dee-742755f1b390.png)

**Comment by theRTC204** [comment]
The problem with hiding those rows is we don't have a way of knowing which predictions are valid... You are seeing that many because at that moment every one of them is potentially valid. As you add more data, the ones that no longer work are automatically removed.

There are already a number of features meant to help summarize the information for people who only care about the basic stuff.

We have the visual graph above the table as the simplest view. The we have the aggregate probability, so that you can make a decision on what is most likely to be a real result.

And for those, such as myself, who want the granular view, we have the individual prediction probability.

All that is to say, after adding just 2 periods worth of data, the list is short and easy to digest.

**Comment by doopl** [comment]
I realise the table will usually be reduced to a manageable size fairly early in the week, though with certain values it will still be quite bloated on Monday afternoon (or even later with the fudge factor in effect).

I do think there are some users who would like to check the site on Monday mornings and at that point the table often isn't very readable. The aggregate probabilities of each pattern are probably the most important bits of information on the table at that stage of the week. If those were broken out to a more prominent location that would certainly help, in lieu of making changes to the table itself.

**Comment by theRTC204** [comment]
We talked about putting the aggregate probabilities into a pie chart. At this point it's a matter of finding a good location for it.

Perhaps that will help with streamlining the summary a bit better.

**Comment by doopl** [comment]
Hmm, yeah a pie chart sounds good! :)

**Comment by theRTC204** [comment]
@mikebryant do you have any thoughts on optionally hiding low probability rows?

I'm thinking something simple such as the following might be a decent compromise.

- A toggle switch to hide rows below some predefined probability.
- Default behavior shows all rows.
- While enablee, show a message at the bottom of the table indicating some rows are hidden.

The risk here I think is that probabilities can swing pretty dramatically as more sell prices are provided. This could lead to patterns which were previously hidden popping up seemingly out of nowhere because they were previously below the "show" threshold.

**Comment by mikebryant** [comment]
That would be a reasonable thing. If it's opt-in that makes it more acceptable to me. I really like the table being the detailed view.

A more complicated alternative that would be to have the whole table be a tree structure, where you can expand first the patterns etc, and if not expanded they present the aggregate for that subset. Not sure if that's worth the complexity.

I'm open to making the aggregated probabilities more prominent

**Comment by theRTC204** [comment]
I've summarized the proposal into a new issue in #192 to refocus the discussion. Going to close this for now. Thank you @doopl for the suggestion!
