### ISSUE TITLE
Sunday prices?

### ISSUE THREAD

**Issue by alecsprinkle** [mikebryant/ac-nh-turnip-prices#200]
When I input my value for Monday morning, it gives me a Sunday buy price in the table instead of putting it on Monday morning. Am I reading that incorrectly? If I put a price into Monday PM, it adds it to the Monday morning on the table.

I bought on Sunday for 100, and inputting 75 for this morning puts it on a Sunday input instead of Monday.
![Screen Shot 2020-04-20 at 9 08 03 AM](https://user-images.githubusercontent.com/64022007/79761005-80032480-82e6-11ea-99c0-3dfbb8f75bf0.png)
![Screen Shot 2020-04-20 at 9 08 08 AM](https://user-images.githubusercontent.com/64022007/79761012-82657e80-82e6-11ea-9b7b-48905712ce18.png)

**Comment by alecsprinkle** [comment]
Never mind. I'm dumb. Everything is just shifted over.

Nothing to see here.

**Comment by doopl** [comment]
If the layout is broken it could be worth keeping this open so it can be looked at. Knowing which device and browser you were using would probably help with that.

Also judging by the appearance of the table you might not have refreshed the page in a while. You could try that to see if it fixes the issue.

**Comment by alecsprinkle** [comment]
I'm running Safari 13.0.5 on a Mac (on Catalina 10.15.3)

It was loaded fresh this morning when I input everything.

**Comment by alecsprinkle** [comment]
The page looks correct now. The "Reset Turnip Prophet" link looks different now, too (in a good way). Previously it looked like an icon of stacked paper, now it's a link. This one seems correct. Columns are aligned.

![Screen Shot 2020-04-20 at 10 33 39 AM](https://user-images.githubusercontent.com/64022007/79769990-6962ca80-82f2-11ea-8c00-2961de765c46.png)

**Comment by theRTC204** [comment]
@alecsprinkle based on your description of the look of the button, what you're describing is an issue with your browser having an outdated cached version of the app.

Last week there was a bug in the way the app was being cached - the index file was being loaded freshly, but the other assets (CSS, JS, icons, images) were being read from cache. This resulted in a number of weird scenarios, such as what you are describing.

Now that the bug is fixed, and you are running the updated version of the code, this shouldn't be a problem going forward. That said, if you experience something like that in the future please open another issue!

Cheers!
