### ISSUE TITLE
Web site not working on Microsoft Edge

### ISSUE THREAD

**Issue by longob** [mikebryant/ac-nh-turnip-prices#208]
Hello,

The web site https://turnipprophet.io/ was working with Microsoft Edge up until a couple of days ago.  Now it no longer works.  It still works on Chrome mobile., but not Edge on PCs.

Thanks!

**Comment by Beznet** [comment]
I tried both Edge 81 on Windows 10 and macOS Catilina and they were both working fine. Are there any particular errors or problems you were seeing? The more info the better as we can identify the potential problem more accurately.

**Comment by BrandonDenton** [comment]
Edge 44.18362.449.0 did not load the trend graph or data points, though I am using an outdated version since I only take essential Windows 10 updates and religiously scrub fluff. Does the problem persist after allowing the browser to update itself?

**Comment by longob** [comment]
Hi,

Thanks for the reply!  No particular errors, but most things don't appear on the screen.  Attached is an example screen shot.  The table and graph also do not show.  I tried this on two different computers and go the same results.  They are running the Edge that came with Windows 10 (not the new Chromium Edge).  The web site works fine with Chrome on my phone.

Thank you,
-Bob

________________________________

**Comment by theRTC204** [comment]
My advice would be to upgrade to Edge 80 or newer - the old Edge based on EdgeHTML is no longer being updated and doesn't support much of the modern web's standards.

This is likely due to something in our code that depends on a feature that EdgeHTML does not support - we could investigate a polyfill, but there probably aren't many people using classic Edge.

@mikebryant do you have any stats in GA that show how much traffic is coming from Edge 18 or lower?

**Comment by mikebryant** [comment]
~4000 people ever, ~0.4% of the total user base

If it's trivial I guess I don't mind it being fixed, but if it's complicated, I'm not hugely interested in supporting old browsers.

And I don't have Edge, or indeed Windows, to be able to test on myself

**Comment by theRTC204** [comment]
Yeah, for such a low percentage it's not ideal... I'm not particularly fond of adding a bunch of polyfills to websites as they tend to create bloat/slowdown.

If I find some time in the next few days to test out why the site isn't working on classic Edge, I can see if there is a quick lightweight polyfill - if not, we'll leave it.

**Comment by FrederikGoovaerts** [comment]
I quickly checked, there's an object spread operator on line 232 of `predictions.js`. Non-chromium-based Edge supports ES6 but not fancy stuff like that, so if you want compatibility without any compilation or polyfills, there's gonna be some rewriting involved.

I still have the older Edge, I can try and figure out if the problem spots are easy to solve and not too ugly, to have this extra compatibility. Your call. Though I do acknowledge that most people SHOULD use a less quirky browser. If it's deemed not important, just close the issue, otherwise I'll devote a quick 15 minutes to check feasibility.

**Comment by mikebryant** [comment]
@FrederikGoovaerts Thanks for offering, and sorry for not getting back to you sooner, but I'm going to decline. I don't think I want to devote any effort to supporting or maintaining this on EdgeHTML
