### ISSUE TITLE
Getting 0-999 / 999-0 error for 2 consecutive weeks

### ISSUE THREAD

**Issue by vialynv** [mikebryant/ac-nh-turnip-prices#234]
Hi guys,

I've been using Turnip Prophet for the past 2 weeks and I've encountered this problem the second time today when after I keyed in Wed AM price.

I do not time travel, have not hosted anyone from time travel consoles, have not traveled anywhere to buy my turnips and I have only 1 user on my Switch Lite. And the numbers are all correct too. I'm playing with my sister (she has her own console) and we check each other's prices everyday along with our own. 

I don't have the screenshot for last week since I've reset the page for this week, but last week was the first time I bought and sell turnips. My price rocket to 459 bells last week at Friday PM and the calculator gone haywire the AM that day. 

For this week's numbers, here's the premalink: https://turnipprophet.io?prices=106.41.37.33.29.90.......&pattern=1

And the screenshot:
![image](https://user-images.githubusercontent.com/64116099/79934186-84fdda80-8484-11ea-91e9-bc7e165905e6.png)

Hope these are helpful for you. Thanks!

**Comment by theRTC204** [comment]
A couple things don't quite line up here.

For one, if last week was in fact the first time a resident bought Turnips on your island, then you were locked into a Small Spike - there is no way around that, it's hard coded as such in the game. You've indicated in this week's data that you had a Large Spike last week.

That also means a sell price as high as 459 would be impossible... The ceiling on a Small Spike is 220, no matter what your buy price was. The highest possible rate on a Small Spike is 2.0, and the highest possible buy price is 110 ever.

Both of those details mean that last week could not have been the first week Turnips were bought by a resident of your island.

Now all that being said, I'm away from my computer to I can't do a deep dive into the math on your numbers quite yet.

**Comment by vialynv** [comment]
Hmmm... I started playing on Sunday afternoon, so I missed buying the first batch of turnips, but I got Nook's Cranny built the first week so I can check turnip prices. The first time I bought turnip was 12th April, the Sunday before the current batch. Perhaps I should have counted the week I started playing ACNH instead of buying turnips?

**Comment by theRTC204** [comment]
There is no value in tracking prices between weeks - other than to understand your previous week's pattern.

What I mean is, the entire week's worth of prices (your Sunday buy price, and the 12 periods of sell prices) are calculated up-front on Sunday before Daisy Mae shows up on your island.

The First Time Buyer flag is important because that previously mentioned up-front calculation is actually performed _twice_ the very first time you buy Turnips. The first run, before Daisy shows up on Sunday, and then assuming "today" (being a Sunday) was the first time you bought, that calculation is run _again_ after Daisy leaves, causing an entirely new set of numbers to be used for your sell prices that week. The act of buying triggers the "first time" flag.

A caveat ... while "first time buyer" can only happen one time ever under normal game play, we do know that time traveling can trigger unusual behaviors. We don't have hard data here, but it could be possible that traveling backwards past the point of your first buy could potentially result in unsetting that flag, but this is completely speculation on my part.

We do know that time traveling does result in the calculation being done again, which I suspect was a deliberate attempt on Nintendo's part to prevent exploitation of a good price week.
