### ISSUE TITLE
Min/max prices not reachable

### ISSUE THREAD

**Issue by thetruegamer** [mikebryant/ac-nh-turnip-prices#25]
I forgot my Monday AM prices, so I just entered the next 3 prices. The table shows me that my possible prices for Monday AM are 86..92, but if I update my Monday AM prices with either 86 or 92, no pattern is found, whereas with 87 to 91 it works fine.

I saw #8 but I'm not sure it's exactly the same issue. Sorry if it is.
If this is a different issue specific to these prices, here are the values to reproduce : buy price of 102, Monday PM 84, Tuesday AM 79, Tuesday PM 76.

**Comment by mikebryant** [comment]
The tool only does forward prediction, not backwards (because really, who would need to predict the past)

So that range for Monday AM is the price range given the buy price from Sunday - but not taking into account the information from Tuesday.

When you put in 86, it then tries to predict forwards from that and finds it would be incompatible with later values, so gives you nothing.

This is basically not an issue, I think. Just leave Monday AM blank - you don't know what the value should have been anyway.
