### ISSUE TITLE
Date calendar system for Turnip Prophet

### ISSUE THREAD

**Issue by Yapsonark** [mikebryant/ac-nh-turnip-prices#251]
I was thinking it would be very helpful to the time traveler if you have a date system built in so when we fill in our info we can set sundays date and each day has its own number.

For eg i've been time traveling all of  next week  which is

Sun-Sat
April 26th - May 2nd

Having those number shown with each day (Mon, Tues, Etc..) Would be very helpful since there is alot of flying thru the system settings to change the dates searching for the best sell price.

I thought this could be a effective feature.

Thanks

-Sorry if this was the wrong place to post this. If so, you're welcome to delete the post

**Comment by theRTC204** [comment]
Every time you time travel, the prices are recalcuated. You cannot predict a price pattern if you time travel even once in a given week.

The prices are calculated using a random seed value which is randomly generated out of uint32, meaning there are exactly 4,294,967,295 possible values that could be used to generate weekly prices. When you time travel, a new seed value is randomized, and the Turnip calculations are run again.

Essentially what I am getting at is there is no point to tracking any data if you are participating in any time traveling.

**Comment by Yapsonark** [comment]
Thats strange because the predictions have always been bang on and on friday was 100% large spike which worked but I only got 327 with potential up to 594

If thats true thats too bad, i'm not trying to get unlimited bells but i think it would be fun to sell with turnip.exchange just once.

Thanks for the reply!

**Comment by theRTC204** [comment]
I should clarify. The calculations are only run when you actually time travel.

So, let's say for example you bought on Sunday, then Monday AM and PM pass, and you decide to time travel to Thursday PM.

The act of time traveling would have reset your calculations, so in this example there would have been two different sets of values.

The prices for Monday, Tuesday, Wednesday and Thursday AM. Then the prices for Thursday PM, Friday & Saturday.

If you at any point travelled backwards in time, not only would your Turnips immediately go rotten, but you would also get yet another seed resulting in all the previous values being lost forever.

**Comment by Yapsonark** [comment]
Ah! so by jumping to AM then PM in order each day until you reach Thursday is alot of work but safe perhaps? 

Skipping one of the AM/PM's and it resets the seed? That's my theory based on 1 flawless travel each day from Sunday to Friday with prophet accurately tracking it. One person who listed 650 also posted their Discord and he explained using prophet he was able to time travel and get that price. It's where I got the idea. It might have been a fluke thou :P

I could be wrong but based on my first success, i'm curious to try again.

If I haven't overstepped somewhere, i'll post my findings. 
Thanks for your reply's! :D

**Comment by theRTC204** [comment]
I have not personally tested this, so take it with a grain of salt.

It is my belief that time traveling forward is likely fine - I believe this because it would be difficult (and perhaps even impossible) to know the difference between natural forward time when someone leaves their console off for a few days, compared to changing the system clock to jump ahead.

However, it would be quite easy to know that time has gone backwards by simply comparing the current time against the last time the game was played. Since time only goes forward, it would be very simple to know that if the "now" time is less than the "last" time, clearly time traveling has taken place.

There's also nothing to gain from resetting the calculations when you travel forward - after all, it is believed that the calculations are run again as a means of preventing repeated exploitation of a High Spike week. If you seed a High Spike and time travel forward to the peak day, you can't return to Sunday to buy more Turnips to then move forward again and sell on the same spike.

But, as I said at the start, I haven't personally tested this - it's purely a theory based on nothing more than how I would approach this problem as a programmer myself. :man_shrugging:

**Comment by Yapsonark** [comment]
Some day soon I hope to dive into some programming myself.

You could I guess, buy sunday and slowly push forward until you get your spike, if it fails just sell to turnip.exchange. It would be fun thou to get a large 500-650 spike and share it with people :)

Considering the insane amount of work it takes to simply attempt a large spike. 
I'd likely only share it once.

**Comment by mikebryant** [comment]
This tool is only concerned with moving forwards in time (as far as I'm aware, going backwards resets the prices anyway, so any data you collected is no longer valid)

Given that, I don't think dates are really useful - knowing the week's data is all you need, once you skip past that you just want to reset all the data and start over

Thanks for your interest though, and may the Turnip RNG be good to you :)
