### ISSUE TITLE
Range value incorrect

### ISSUE THREAD

**Issue by happiehappie** [mikebryant/ac-nh-turnip-prices#255]
Not sure if this is the right place to post this. but this is my wife's trend from thursday night 
https://turnipprophet.io?prices=98.74.69.64.60...50.110....&pattern=3
friday morning stated 89 to 138
but friday morning ended up being 152

one info that might contribute to the topic.. cranny was closed on wednesday

**Comment by mikebryant** [comment]
I think that this must have been because that week was the first time that a resident on your island bought turnips on your own island - you'll see that if you change first time buyer to be true you get a prediction: https://turnipprophet.io?prices=98.74.69.64.60...50.110.152...&first=true&pattern=3

I hope the tool continues to be useful for you, and you turn a profit :)
