### ISSUE TITLE
The price prediction percentages are misleading and based on flawed logic

### ISSUE THREAD

**Issue by HexZyle** [mikebryant/ac-nh-turnip-prices#333]
The percentages that appear on Turnip Prophet's left hand side are very misleading once data has been entered into the form. The percentages represent the ratio of how many of the possible patterns fit the data presented, not the likelyhood of each pattern. This can and does lead to people assuming the graph is predicting the chances of them having a particular pattern is increasing, when this is not so. The chances of a pattern occuring do not change, regardless of how many invalid models are removed, as the pattern is selected at the start of the week.

This leads to a Monty Hall problem. If you have a 5% chance of a decreasing pattern (goat) at the start of the week, and a 20% chance of a Large Spike (car), the Chance of a decreasing pattern does not increase to 90% if all but one model (door) of Large Spike is eliminated as impossible. You are not getting a pattern (prize) based on the data observed and models eliminated (doors opened), you are observing data and model elimination (doors opened) based on the pattern (prize) you have.

The fix is to retain the percentage distribution from the start of the week throughout the entire week, as whatPattern = nextPattern is not affected by the particular model of the pattern. If you wish to scale it based on the information available, scale the percentages to match 100% **only** when a pattern's possibility is eliminated. If your distribution was 20% | 30% | 15% | 35% because of a fluctuating pattern last week and the possibility of decreasing and small spike patterns have been eliminated, scale the remaining 20% | 30% to [40% | 60%]. The possible models of the remaining patterns are irrelevant here.

I notice people suggesting profit predictions based on the model percentages. If this error is not corrected, further predictions based on these percentages will be incorrect also.

**EDIT: I made some conflations between prior probabilities and conditional probabilities in this post and did not realise that the calculations in the tool do the latter quite well. I think I may have made a large mistake in this post as I was considering this is comparison to the Monty Hall problem, where you are given the choice to re-select what result you get and the flaw comes from thinking that the two events are similar and the probabilities are the same - the exact mistake I have made here.**

**Comment by peter50216** [comment]
> The fix is to retain the percentage distribution from the start of the week throughout the entire week, as whatPattern = nextPattern is not affected by the particular model of the pattern. If you wish to scale it based on the information available, scale the percentages to match 100% **only** when a pattern's possibility is eliminated. If your distribution was 20% | 30% | 15% | 35% because of a fluctuating pattern last week and the possibility of decreasing and small spike patterns have been eliminated, scale the remaining 20% | 30% to [40% | 60%]. The possible models of the remaining patterns are irrelevant here.

A simple argument to see why this is wrong:

Let's say we further split the large spike pattern into two different pattern of same probabiliy.

For example, we call the pattern that have `peakStart = randint(2, 9);` early (in range `[2,5]`) an `early-large-spike` pattern, and `6 <= peakStart <= 9` an `late-large-spike` pattern. It's clear that the distribution would be 20% | 15% | 15% | 15% | 35% for `flucutating | early-large-spike | late-large-spike | decreasing | small-spike`. Then what if the filled data makes the late-large-spike | decreasing | small-spike impossible?

Using your method, the chance for flucutating | early-large-spike would then be ~57% | ~42% (scale up from 20% | 15%). But if we don't sub-divide the pattern then the chance for fluctuating | large-spike would then be 40% | 60%. The "probability" of fluctuating that you're getting from your method is now entirely depends on how you sub-divide the large-spike patterns, which is obviously wrong.

---------------------

Or let me give a toy discrete example. (The problem we have is actually also discrete with a large space btw):

Let's say we are now only drawing a pair of values from `[(1, 0), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (2, 0), (3, 0), (4, 0), (5, 0)]`, all of them are of equal probability (10%), and we have the following "patterns":

`Pattern A`: values can be either `(1, 2)`, `(1, 3)`, `(1, 4)`, `(1, 5)` or `(1, 6)`
`Pattern B`: values can be either `(1, 0)`, `(2, 0)`, `(3, 0)`, `(4, 0)` or `(5, 0)`

It's clear that probability of pattern A and B is 50% and 50%.

Now say we know that the first number of the pair is `1`. Is the probability that you're getting pattern A and pattern B still 50% / 50%?

**Comment by HexZyle** [comment]
> The "probability" of fluctuating that you're getting from your method is now entirely depends on how you sub-divide the large-spike patterns, which is obviously wrong.

It's obviously wrong because you're trying to subdivide the large spike pattern when there are only four patterns. As I said in the paragraph you quoted, whatPattern = nextPattern is not affected by the particular model of the pattern, and so discrete models of patterns should be disregarded when calculating probability of having a particular pattern. Whether or not the late large spike is impossible or not based on the known data has no effect on the fact that large spike had a 30% chance of being assigned on [line 142.](https://gist.github.com/Treeki/85be14d297c80c8b3c0a76375743325b)

> Let's say we are now only drawing a pair of values from [(1, 0), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (2, 0), (3, 0), (4, 0), (5, 0)], all of them are of equal probability (10%), and we have the following "patterns":
> Pattern A: values can be either (1, 2), (1, 3), (1, 4), (1, 5) or (1, 6)
Pattern B: values can be either (1, 0), (2, 0), (3, 0), (4, 0) or (5, 0)
> It's clear that probability of pattern A and B is 50% and 50%.
> Now say we know that the first number of the pair is 1. Is the probability that you're getting pattern A and pattern B still 50% / 50%?

Yes, the probability that you have Pattern A or B is still 50% / 50%. The question is irrelevant to the data because your odds do not change simply because you know which results you didn't get. You got the pattern before a model was selected or data was generated.
Your question would be better worded by asking "what is the probability the data matches Pattern A or Pattern B"?, and I mentioned this in the OP
>  The percentages represent the ratio of how many of the possible patterns fit the data presented, not the likelyhood of each pattern

**Comment by peter50216** [comment]
> Your question would be better worded by asking "what is the probability the data matches Pattern A or Pattern B"?, and I mentioned this in the OP
> 
> > The percentages represent the ratio of how many of the possible patterns fit the data presented, not the likelyhood of each pattern

I think you're confusing the "prior probability" with "conditional probability" here. The shown probability is NOT about the prior probability of each pattern, but the conditional probability `P(some pattern happned | the observed data)`.

I mean, the prior probability of course don't change when you input the data, but showing that is not more "useful" or "correct" in any sense, and what the user want to know is the conditional probability, the chance that the pattern happened **given the inputted data**.

> Given that you only know the first number of the pair, what is the probability you're getting Pattern A?

Depends on WHAT the first number is. We want to know the probability `P(Pattern A | first number = some number)`.

**Comment by seankao31** [comment]
> > Now say we know that the first number of the pair is 1. Is the probability that you're getting pattern A and pattern B still 50% / 50%?
> 
> Yes, the probability that you have Pattern A or B is still 50% / 50%. Your question is irrelevant to your data.
> You could assert that it is impossible that you have Pattern B if no subsets of Pattern B match the data, but this is not a statement of probability, but instead logic.
> If even just one subset of B matches your data, and the chance of Pattern B was initially 50%, then the probability that your subset is in Pattern B is still 50%.

You seem to completely fail to understand conditional probability. The answer is 1/6 and 5/6.

> Given that you only know the first number of the pair, what is the probability you're getting Pattern A?

1/6 obviously, regardless of which the first number is, coincidentally. I'm curious about what you're trying to say through this example.

**Comment by HexZyle** [comment]
> 1/6 obviously, regardless of which the first number is, coincidentally. I'm curious about what you're trying to say through this example.
Yes, coincidentally I didn't create an example that demonstrated a difference between the two. Anyway, I believe I have gotten off track discussing the differences between prior probability and conditional probability, which might not be my strongest case.

> I think you're confusing the "prior probability" with "conditional probability" here. 

I'm not confusing them, I'm suggesting the prior probability be used, because the implementation of the conditional probability is awful. The number of false positives the tool generates makes any attempt at guessing what pattern you have based on the ratio of remaining viable models is laughable.

One model (the model you have) may fit the data perfectly, while all the other models could possibly generate the data displayed but not with near as much likelyhood. But Turnip prophet treats all models as equals, and behaves as if the number of impossible models in a pattern mean that that pattern was less likely to result in the data.

**Comment by peter50216** [comment]
> I'm not confusing them, I'm suggesting the prior probability be used, because the implementation of the conditional probability is awful. The number of false positives the tool generates makes any attempt at guessing what pattern you have based on the ratio of remaining viable models is laughable.

Please have some real example on the "false positives" you're claiming, rather than saying others hard work to an OSS as "laughable" or "awful".

This tool is NOT based on some experience / data based model that we're making up, **the conditional probability is based on the reversed real game logic**, and that the probability of each models are also calculated according to the code.

It's not like we just come out with some possible "patterns" that we're observing and claiming that they have equal probability, it's that the reveresed code actually says so.

**Comment by seankao31** [comment]
> Anyway, I believe I have gotten off track discussing the differences between prior probability and conditional probability, which might not be my strongest case.

No, actually this is the single most important part. Please do elaborate.

**Comment by ZZZZzzzzac** [comment]
Sometimes probability is counterintuitive and may be very confusing, my first solution is to make an easy but extreme hypothesis, if doesn't work, then do equation and math staff, if still confusing, I will just run a bunch of Monte Carlo simulation, which is usually the most convincible and reliable method

```
# using @peter50216's example:
bag = [(1, 0), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (2, 0), (3, 0), (4, 0), (5, 0)]
N = 100000
draw = [bag[np.random.randint(0,10)] for i in range(N)]
```

```
# no prior knowledge
Pattern_A = 0
for i in draw:
    if i[1]>0:
        Pattern_A += 1
print("pattern A: {:.4f}  pattern B: {:.4f}".format(Pattern_A/len(draw),1-Pattern_A/len(draw)))
```
output: pattern A: 0.4997  pattern B: 0.5003

```
# knowing first number is 1
know = [i for i in draw if i[0]==1]

Pattern_A = 0
for i in know:
    if i[1]>0:
        Pattern_A += 1
print("pattern A: {:.4f}  pattern B: {:.4f}".format(Pattern_A/len(know),1-Pattern_A/len(know)))
```
output: pattern A: 0.8328  pattern B: 0.1672

**Comment by NeatNit** [comment]
I want to throw in my 2 cents. One of the first things they teach in a probability course is Bayes' Rule:

`P(A|B) = P(B|A) * P(A) / P(B)`

In this case, that would translate to:

`P( some particular pattern | data ) = P( data | some particular pattern ) * P( some particular pattern ) / P( data )`

Where "some particular pattern" refers to a single row in the table.

The left-hand side is what we want to display to the user, the right-hand side is entirely possible (albeit not trivial) to compute:

`P( data | some particular pattern )` - this, in my opinion, is the hardest one to compute, and requires going over each type of pattern and considering the various random rolls involved. It's hard, but it's not absurd or impossible. Just time consuming, and high likelihood of making a mistake somewhere.

`P( some particular pattern )` - this is relatively trivial to compute based on the previous week's pattern (when available) and a handful of random rolls that determine the phase lengths.

`P( data )` - thanks to [this trick](https://en.wikipedia.org/wiki/Bayes%27_theorem#Extended_form), this is actually the sum of `P( data | pattern i ) * P( pattern i )` over all possible patterns.

This means that once the code correctly calculates `P( data | pattern ) * P( pattern )` for each possible pattern, the problem is solved.

The question is, is this what Turnip Prophet already does? I don't know; I got too lost in the code to figure it out.

**Comment by NeatNit** [comment]
> The question is, is this what Turnip Prophet already does? I don't know; I got too lost in the code to figure it out.

I've now taken a closer look at the code. I believe it does do exactly this.

**Comment by ZZZZzzzzac** [comment]
> Still, it's obvious you guys did your homework on this! :)
#48 <= this, if you're interest

**Comment by NeatNit** [comment]
> current code written by @peter50216 is using iterative method, multiplying probability of each step instead of using pure bayes equation, if ignore the precision problem then these two approach should be equivalent

Two questions:
1. if I understand correctly, the "iterative  method" you're talking about is the way it calculates `P( data | pattern )`, right? But then it uses that result in Bayes' equation. Since calculating that probability is hard, doing it step-by-step is as good a method as any, assuming it's correct. Which brings me to...
2. Has the code been verified to predict well? Specifically, with a given pattern and data, it's possible (I might even say trivial) to generate 10000000 weeks using that pattern, see how many of them got exactly the correct daily prices, and compare with the predicted `P( data | pattern )`. If I find myself with any amount of free time (which would be a miracle), I might even try doing that myself.

**Comment by peter50216** [comment]
> 2. Has the code been verified to predict well? Specifically, with a given pattern and data, it's possible (I might even say trivial) to generate 10000000 weeks using that pattern, see how many of them got exactly the correct daily prices, and compare with the predicted `P( data | pattern )`. If I find myself with any amount of free time (which would be a miracle), I might even try doing that myself.

I didn't run any simulations to verify the result when writing this, but there was another issue about prediction and I wrote some simulation there: https://github.com/mikebryant/ac-nh-turnip-prices/pull/132#issuecomment-623850917

So there's at least one instance of data that has about correct probability, so the algorithm is not like conpletely wrong. But yeah there's no extensive testing from simulations afaik. It should be pretty easy to change the simulation code there to test more cases though.

**Comment by ZZZZzzzzac** [comment]
> if I understand correctly, the "iterative method" you're talking about is the way it calculates P( data | pattern ), right? But then it uses that result in Bayes' equation. Since calculating that probability is hard, doing it step-by-step is as good a method as any, assuming it's correct. Which brings me to...

In fact the current code calculate exact probability of input data, `P(a1,a2,a3,a4...)` by multiply `P(a1)*P(a2|a1)*P(a3|a1,a2)*....` instead of calcuating `P(pattern|data) `using prior knowledge about PDF and CDF. This is what I said "not pure bayes", it actually calculate probabilies of every single price combination, not just some pattern or subpattern.

And this implementation makes simulation harder, say during 12 time period in a week, each have 50 potential prices (like 90~140), so there will be `50^12=2.4e20` price combination which is too big for simulation method to check whether `P(a1,a2,a3,a4...)` is correct or not.

**Comment by NeatNit** [comment]
> In fact the current code calculate exact probability of input data, `P(a1,a2,a3,a4...)` by multiply `P(a1)*P(a2|a1)*P(a3|a1,a2)*....` instead of calcuating `P(pattern|data) `using prior knowledge about PDF and CDF. This is what I said "not pure bayes", it actually calculate probabilies of every single price combination, not just some pattern or subpattern.

I'm not seeing this, can you show me where in the code this happens? When I read the code it seems like it does this method *per subpattern*.

Another thing - what happens when some daily prices are missing? Like for example if on Tuesday the player never checks the prices, but does on Wednesday. How does the code deal with that for probability calculations?


> And this implementation makes simulation harder, say during 12 time period in a week, each have 50 potential prices (like 90~140), so there will be `50^12=2.4e20` price combination which is too big for simulation method to check whether `P(a1,a2,a3,a4...)` is correct or not.

That's true, and almost made my say "you're right, it's impossible to actually test this", but then I thought: what if we input an impossibly low base price, like 10 or even 5? I don't think there's any part of the code that's hard-coded to expect the user-given base price to be in [90,110], so everything should keep working, including probability calculations; but then the possibility space becomes much much smaller, and it becomes possible to use simulations to verify the probability calculations in principle.

**Comment by ZZZZzzzzac** [comment]
> I'm not seeing this, can you show me where in the code this happens? When I read the code it seems like it does this method per subpattern.

my statement might be misleading, what I want to emphasize is that it essentially calculate `P(a1,a2,a3...,an)` instead of the whole PDF of an, yet `P(a1,a2,a3...,an)`  is still following subpattern...so you can say it still calculate probabilities of subpattern

As for the missing value, I think it just leave corresponding probability to 1, like in `generate_decreasing_random_price()`
```
let prob = 1;
if (!isNaN(given_prices[i])) {
...
  prob *= rate_pdf.range_limit(real_rate_range);
...
}
...
return prob;
```

**Comment by NeatNit** [comment]
> As for the missing value, I think it just leave corresponding probability to 1, like in `generate_decreasing_random_price()`

But the previous price can affect the next (most notably in a decreasing phase), so not knowing the previous price requires a different calculation for the probability of the next price. I'm not seeing that taken into account here, so I suspect there's some mistake.

This is why I said that calculating `P(data|pattern)` is hard. It needs various branches to deal with different scenarios. Though honestly, it seems like a fun exercise.

Funnily enough, I'm currently in the middle of a probability course in university, and I'm procrastinating my homework in favor of discussing this :P

**Comment by peter50216** [comment]
> But the previous price can affect the next (most notably in a decreasing phase), so not knowing the previous price requires a different calculation for the probability of the next price. I'm not seeing that taken into account here, so I suspect there's some mistake.

The way the probability is calculated is like:
```
P(data | pattern) = P(price 1 | pattern) * P(price 2 | price 1, pattern) * P(price 3 | price 2, price 1, pattern) * ....
```
So when some price point is missing, the term `P(missing price point | previous price, pattern)` is actually 1, so `return 1` sounds reasonable to me here.

Also the simulation case in https://github.com/mikebryant/ac-nh-turnip-prices/pull/132#issuecomment-623850917 is also the case that has missing data inside.

> This is why I said that calculating `P(data|pattern)` is hard.

Yes it's not trivial but I do believe the algorithm we're using is correct now. It would be great if there's some more simulation experiments to confirm this though.

**Comment by HexZyle** [comment]
I took some time to think about this and do some more research on probabilities and I have come to the conclusion that my original assumptions were incorrect.

I apologise for my last comment, it was incoherent and posted late at night as I was frustrated and holding too firmly to my point without considering that I had a base rate bias.

**Comment by NeatNit** [comment]
Here's what's bothering me. Looking at the code that this corresponds to:

https://github.com/mikebryant/ac-nh-turnip-prices/blob/a400ee92180459f07052022133c4d0fcfd3209d7/js/predictions.js#L375-L387

(I had written some incoherent babble here, this is attempt number two)

The current probability calculations basically assume that A=`sellPrices[k] == x` and B=`sellPrices[j] == y` are independent events, that is, `P(A and B) = P(A) * P(B)`, but this is not true at all. More intricate calculations are required.

It might be that this code produces results which are very nearly correct, to within the displayed accuracy, but it is mathematically incorrect.

**Comment by peter50216** [comment]
> The current probability calculations basically assume that A=`sellPrices[k] == x` and B=`sellPrices[j] == y` are independent events, that is, `P(A and B) = P(A) * P(B)`, but this is not true at all. More intricate calculations are required.

That part of code doesn't assume that they are independent events. As I've said the probability was calculated as `P(A and B) = P(A) * P(B | A)`. The `rate_pdf.range_limit` corresponds to the `P(B | A)` part.

**Comment by NeatNit** [comment]
Oh, huh, I somehow missed that whole operation.

**Comment by FoxFireX** [comment]
So I was noticing the percentages changing, and had the same Monty Hall problem thought, and went to submit, but then found that this issue exists. Oh my, that's a lot to read. Honestly, I'm not up to reading all the way through it right now.

Interestingly, as I was writing up my explanation of why I thought things were wrong, I think I've actually come around and convinced myself that maybe they actually are right after all. For my specific case, we started the week with about a 30% chance of decreasing, and a 70% chance of small or big spike. Since then, as the lower prices have continued rolling in, the Decreasing pattern is now at a 50% probability. That didn't make sense to me, but in revisiting it, I'll play the same "extend the Monty Hall game to absurdity" argument, but tailored to this.

Let's say that I'm going to forecast a week that is one million days long. (Bear with me.) In this game, there's a 50% chance that the price will decrease every single day. There's a 50% chance that prices will decrease every single day, with ONE exception, when the price will be One Beeeeeeellion Bells.

We now faithfully track our data, and after 999,999 days, we've seen a decrease every single day. Is the likelihood that we get the massive payday on that final day *really* still 50%? I don't think so. If we had selected the Jackpot pattern, we would only observe this pattern one in one million times. If we had selected the Decreasing pattern, we would observe this pattern EVERY SINGLE TIME. 

So even though the initial selection was 50/50, it's really more accurate to look at it as if I made a selection of 1,000,000 different Jackpot patterns at 1/2,000,000 odds, and a single Decreasing pattern at 1,000,000/2,000,00 odds. By the time I've eliminated 999,999 of the Jackpot patterns, I'm left with a 1/1,000,001 chance of getting that Jackpot I was so hoping for, and a 1,000,000/1,000,001 chance of sorrow and destitution.

Have I traversed the path of mathematical truth? And am I doomed (DOOMED) to a week of disappointing turnip prices?

**Comment by silid** [comment]
I think we are conflating probability and likelihood. (I didn’t study probability so forgive me if I get the terms wrong).

I had fluctuating last week, so this week the probabilities are: 

- 35/100 Small (8 paths)
- 30/100 Large (7 paths)
- 20/100 Fluctuating
- 15/100 Decreasing

However I get to Wednesday and I can see that there are only two large spike patterns left, so the likelihood that I am on one of those patterns has decreased.
Remaining outcomes and percentages should be:

- 8.75/32.32 (27%) Small (2 paths)
- 8.57/32.32 (26.51%) Large (2 paths)
- 15/32.32 (46.41%) Decreasing 

These aren’t what the prophet predicts, so I think there is an error somewhere.

**Comment by peter50216** [comment]
> Remaining outcomes and percentages should be:
> 
> * 8.75/32.32 (27%) Small (2 paths)
> * 8.57/32.32 (26.51%) Large (2 paths)
> * 15/32.32 (46.41%) Decreasing
> 
> These aren’t what the prophet predicts, so I think there is an error somewhere.

The reason is that the possible range for prices of each pattern is not the same.

After you have some input and some patterns are elimated, those 2 remaining paths for small spikes doesn't still "occupies" the whole 8.75 "percent" from the original probabilities, since there's only a fraction of them that corresponds to the price you're seeing. And since the "fraction" is different for different pattern, the final percentage won't be the same as the calculation here.

**Comment by silid** [comment]
@peter50216 - Well done - I hadn't spotted that. The logic is heavily nested which makes it so mind bending.
