### ISSUE TITLE
Turnip prices return no patterns 

### ISSUE THREAD

**Issue by Lyranove** [mikebryant/ac-nh-turnip-prices#363]
My inputs so far are:
First-time buyer: yes
Last week: large spike
Bought: 94
Mon am/pm: 75/39
Tues am/pm: 60/49
Wed am: 78
Initially I had first-time buyer as no because I've been doing this a few weeks but if I change it to yes and have the last two prices (Tues pm and Wed am), I get a small spike pattern that should show with all the other prices (screenshot uploaded for reference). However, adding any other prices returns no patterns. Any advice would be appreciated.
Thanks! 
![Screenshot_20200513-104108](https://user-images.githubusercontent.com/65282921/81797320-8449e880-9506-11ea-912d-dca0365a8942.jpg)

**Comment by theRTC204** [comment]
Let's break down the math. There are four possible patterns in the game.

**Pattern 0 (Fluctuating)** has five phases (_high, decreasing, high, decreasing, high_). The first phase can be anywhere from 0 to 6 periods in length. In the first phase, the starting `rate` is between 0.9 to 1.4; your buy price of 94 means the lowest possible initial price for this phase would have been 85.
```
94 * 0.9 = 84.6
84.6 + 0.99999 = 85.59999
(int) 85.59999 = 85
```
So, that rules out a high phase, however as I mentioned a moment ago, the first phase can be 0 periods in length. So, we check the second phase, which is either 2 or 3 periods long, with a starting rate of 0.6 to 0.8, then decreases by 0.04 to 0.06 for each period in the phase. Your buy price of 94 would have a peak of 76 in the first period of this phase.
```
94 * 0.8 = 75.2
75.2 + 0.99999 = 76.19999
(int) 76.19999 = 76
```
So, your value for Monday AM matches a Fluctuating pattern. Then, we move onto Monday PM, where you have entered a value of 39. As I mentioned previously, the most that a rate can decrease between periods in this phase is 0.06, and from a sell price of 75 we can determine that your `rate` on Monday AM would have been between 0.78724 to 0.79787. Since we're looking for the lower bound, we'll use the lowest `rate` and decrease it by the most possible, and we end up with a lower bound price of 69.
```
0.78724 - 0.06 = 0.72724
94 * 0.72724 = 68.36056
68.36056 + 0.99999 = 69.36055‬
(int) 69.36055‬ = 69
```
At this point, we've determined that your Monday PM price of 39 is impossible.

**Pattern 1 (Large Spike)** has three phases (_decreasing, high spike, random low_) where the first phase is between 1 to 7 periods, and the starting `rate` is between 0.85 to 0.9. Right off the hop, we can determine that your Monday AM value is out of range for this pattern.
```
94 * 0.85 = 79.9‬
79.9‬ + 0.99999 = 80.89999‬
(int) 80.89999‬ = 80
```
So, we know it's not a Large Spike this week.

**Pattern 2 (Decreasing)** has a single phase (_decreasing_) where the starting `rate` is between 0.85 to 0.9, and is reduced by 0.03 to 0.05 every period thereafter. Using the same calculation as Pattern 1, we can also rule out this pattern as well.

**Pattern 3 (Small Spike)** has three phases (_decreasing, spike, decreasing_) where the first phase is between 0 to 7 periods, with a starting rate of 0.4 to 0.9, which is then reduced by 0.03 to 0.05 for each period thereafter. Using the previous calculations, we can see that your Monday AM value fits within the range.
```
94 * 0.4 = 37.6
37.6 + 0.99999 = 38.59999
(int) 38.59999 = 38
```
```
94 * 0.9 = 84.6
84.6 + 0.99999 = 85.59999
(int) 85.59999 = 85
```
So, then we move onto Monday PM which you input a value of 39, and this is where things start to break down. If we assume that you rolled a low `rate` on Monday AM, then your Monday PM value would be within range; for example:
```
36 / 94 = 0.38297
0.38297 + 0.03 = 0.41297
```
```
0.4 - 0.03 = 0.37
```
_Note: In the above two blocks, I've demonstrated that in isolation a value of 36 for Tuesday PM is possible, because the effective rate is roughly ~0.38 which is above the lowest possible rate of 0.37._

However, we know from the fact that your Monday AM value was 75, that your effective rate is actually between 0.78724 to 0.79787, meaning the lowest effective rate you could possibly half in this period is actually 0.73724, making your lowest possible sell price 70 for this period.
```
0.78724 - 0.05 = 0.73724
0.73724 * 94 = 69.30056
69.30056 + 0.99999 = 70.30055‬
(int) 70.30055‬ = 70
```
So, here we have ruled out Decreasing as your possible pattern, which means there are no longer any value patterns for your inputs.

----

All this is to say, there appears to be an issue with your inputs. It could be your Monday AM price is wrong, or the Monday PM price, or perhaps even both.

This begs a few questions:
1. Are you absolutely certain that all your values are from the same island?
2. Are you absolutely certain that no one using your Switch did any time traveling?
3. How confident are you that the values entered were entered correctly?

**Comment by Lyranove** [comment]
Thank you for such a detailed reply to my query. I'm certain the values are from my island and are correct, and while I don't time travel I can't rule that out as I'm not the only one using it - unlikely my kids will admit to it mind but that's probably the cause.
