### ISSUE TITLE
First Time Buyer Shows All Small Spike Patterns

### ISSUE THREAD

**Issue by snatefinch** [mikebryant/ac-nh-turnip-prices#39]
When putting in a buy price and checking the box for first time buyer, instead of showing you only the options for small spike for your buy price, it shows all options for each buy price. I do not believe this is the intended functionality, I would assume you want to only show the options for your buy price. My guess that there is just a small issue with the JS that is not hiding the other options.

I would love to contribute to this project as well, I feel like more can be added to the already great tool you made (my thought is some sort of graph with a cone of uncertainty, since I am in Florida and love the cone of uncertainty from Hurricane season).

![image](https://user-images.githubusercontent.com/329724/78794598-f700fa80-7981-11ea-9728-9164063e8f59.png)

**Comment by theRTC204** [comment]
Sorry, your assumption is incorrect.

When you buy Turnips on your island for the very first time ever, two things happen.

First, you are locked into Pattern 3 (decreasing, spike, decreasing) and secondly on Monday your buy price is regenerated. The latter of those two things makes your buy price irrelevant for your first week, which is exactly why the feature is doing what it is doing.

Since your buy price is unknown in your first week, the tool returns you values for every possible buy price, and then slowly narrows those down as you provide the tool with more sell prices throughout the week.

**Comment by snatefinch** [comment]
Ahhh, did not realize that the initial buy price is regenerated. Lots of logic to weed through, didn't see that.
