### ISSUE TITLE
Tracker showing 999 min, 0 max

### ISSUE THREAD

**Issue by silverdragon526** [mikebryant/ac-nh-turnip-prices#417]
https://turnipprophet.io?prices=107.98.130.126.85.80.75......&first=true&pattern=1

My tracker is showing 999 min, 0 max. The graph too is messed up. The first time buyer and last week pattern is correct.

**Comment by silverdragon526** [comment]
Sorry, forgot phone info:

Smartphone (please complete the following information):

Device: samsung galaxy s9
OS: 
Browser: stock browser
Version:

**Comment by tonyvonhsu** [comment]
Mine too.
Was Okay When
https://turnipprophet.io?prices=90.84.80.76.73.119.117.180.....&pattern=3
It predicted 180 for afternoon but went out 204 and then crashed
https://turnipprophet.io?prices=90.84.80.76.73.119.117.180.204....&pattern=3

Also, version 1.3.1 and last week 
Oh! I see, I should mark that it's my first time to buy, then it went right
https://turnipprophet.io?prices=90.84.80.76.73.119.117.180.204....&first=true&pattern=3

**Comment by tonyvonhsu** [comment]
I tried your URL and made it not first time then it went well
https://turnipprophet.io?prices=107.98.130.126.85.80.75......&pattern=1

**Comment by Shirk** [comment]
Might be related - this pattern isn't in the list but the last price (50) is okay - https://turnipprophet.io?prices=101.53.48.45.40.37.50......

Removing the 50 shows that there simply is no match for this scenario which is probably what causes the whole issue. This is the possible ranges for Wednesday afternoon: 
![image](https://user-images.githubusercontent.com/304352/88278310-1118db80-ccda-11ea-9ef5-0fca39fd01d9.png)

31-34 or 91-142, but 50 is spot on in the dead zone in between.

**Comment by effsee123** [comment]
This also happened to me - with a minimum of "infinity" and a maximum of "-infinity". I haven't time traveled, I'm using a MacBook with Google Chrome. I put everything in accurately and I know it was accurate because I kept a log of it via messages among a group of friends in a private Discord.
It was fine before I hit the 367 bells/turnip amount yesterday morning. And by that I mean that it looked like my friends' turnip prophet graphs do, without this whole impossible min of infinity and max of negative infinity. That part makes no sense whatsoever.
[https://turnipprophet.io?prices=107.93.112.128.214.367.214.147.75....&pattern=3](My outcomes this week.)
<img width="1246" alt="Screen Shot 2020-09-03 at 12 12 25 PM" src="https://user-images.githubusercontent.com/70721747/92160696-47bb3900-ede4-11ea-8a59-ec3181e8827f.png">
<img width="1247" alt="Screen Shot 2020-09-03 at 12 12 57 PM" src="https://user-images.githubusercontent.com/70721747/92160711-4d188380-ede4-11ea-96a3-87baf8920d58.png">
<img width="1247" alt="Screen Shot 2020-09-03 at 12 13 23 PM" src="https://user-images.githubusercontent.com/70721747/92160717-4f7add80-ede4-11ea-8657-64c7ce8c80b2.png">

Let me know if there's any additional information you need. I'm only giving you guys this so you have the information, I'm not worried about the inaccuracy for my own sake. But, by all means, if you want me to change something to see what happens or have any other questions, I have no problem doing so to help.

**Comment by neubauje** [comment]
I've been tracking my turnip prices for almost a month now, and when I try to put them into TurnipProphet to see what kind of patterns I've been experiencing, I'm not getting any answers... Just "all patterns" and infinite bounds... Is that *supposed* to happen? Here's the data I'm working from:
8/15/20 - Turnip prices 83 and 78

8/16/20 (Sunday) - Turnips selling for 104
8/17/20 -Turnip prices 98 and 73
8/18/20 - Turnip prices 151 and 378
8/19/2020 - Turnip prices 137 and 133
8/20/2020 - Turnip prices 68 and 64
8/21/2020 - Turnip prices 109 and 140
8/22/2020 - Turnip prices 133 and 94

8/23/2020 (sunday) - Turnip price: 92
8/24/2020 - Turnip prices 118 and 83
8/25/2020 - Turnip prices 80 and 76
8/26/20 - Turnip prices 72 and 132
8/27/2020 - Turnip prices 66 and 61
8/28/20 - Turnip prices 56 and 51
8/29/2020 - Turnip prices 46 and 42

8/30/2020 (sunday) - Turnip price 99
8/31/2020 Turnip prices 138 and 54
9/01/2020 - Turnip prices 86 and 82
9/02/20 - Turnip prices 96 and 91
9/03/20 - Turnip prices 119 and 119
9/04/20 - Turnip prices 134 and 73
9/5/20 - Turnip prices 66 and 56

9/6/20 (sunday)- Turnip price: 103
9/7/20 - Turnip prices 126 and 134
9/8/20 - Turnip prices 79 and 97
9/9/20 - Turnip Prices 136 and 158
9/10/2020 - Turnip prices 154 and 69
9/11/20 - Turnip prices 65 and 62
9/12/2020 - Turnip prices 57 and 54

9/13/2020 (sunday) - Turnip price: 109

**Comment by neubauje** [comment]
What more information did you need?
For what it's worth, I think I was experiencing this issue because I was
time-traveling to make sure to get every price change. I tried going
without time travel, and that seemed to resolve the issue.
