### ISSUE TITLE
Certain entry results in impossible prediction

### ISSUE THREAD

**Issue by RLesser** [mikebryant/ac-nh-turnip-prices#63]
Entered the following data, which gave a prediction where the min price was higher than the max price
<img width="1012" alt="Screen Shot 2020-04-11 at 12 32 27 PM" src="https://user-images.githubusercontent.com/12756127/79049304-dab6c500-7bf0-11ea-8de8-53ac76bbfefc.png">

**Comment by theRTC204** [comment]
Your screenshot suggests that you had two days in a row where the AM & PM prices were identical How certain are you that is correct? While possible, it seems unlikely to me.

**Comment by ZZZZzzzzac** [comment]
It is possible, for pattern3
```
    sellPrices[work++] = intceil(randfloat(0.9, 1.4) * (float)basePrice);
    sellPrices[work++] = intceil(randfloat(0.9, 1.4) * basePrice);
    rate = randfloat(1.4, 2.0);
    sellPrices[work++] = intceil(randfloat(1.4, rate) * basePrice) - 1;
    sellPrices[work++] = intceil(rate * basePrice);
    sellPrices[work++] = intceil(randfloat(1.4, rate) * basePrice) - 1;
```
if `rate = randfloat(1.4, 2.0) = 1.4`, then `randfloat(1.4, rate)=1.4`

**Comment by theRTC204** [comment]
I didn't say it was impossible, I said it was highly unlikely. In any case, the application rules out pattern 3 as soon as you input your Monday AM numbers, which is clearly any issue.

Your Monday AM number is 51, and the lowest pattern 3 (fluctuating) prediction the app makes is 63, way out of range. I'll do some digging into the code and see what I can find.

**Comment by theRTC204** [comment]
Whoops, I confused pattern 3 as fluctuating, when it's small spike. Getting tired... haha. I'll take another look at this tomorrow.

**Comment by gmueller-dev** [comment]
I have run into a similar situation this week:
![image](https://user-images.githubusercontent.com/38698604/79246213-bfd99000-7e3e-11ea-8664-411538705bb4.png)

**Comment by theRTC204** [comment]
I ran these numbers against the algorithm and I feel like I'm seeing an issue.

Assuming the buy price of 102, and a `peakStart` value of 5 or higher (which these values so far suggest), and the RNG gods give the highest possible returns.

Monday AM
`intceil((102 * 0.9) + 0.99999) = 92.79999` returns 92, which matches the 91 you received.

Monday PM
`intceil((102 * (0.9 - 0.03)) + 0.99999) = 89.73999` returns 89, which matches the 86 you received.

Tuesday AM
`intceil((102 * ((0.9 - 0.03) - 0.03)) + 0.99999) = 86.67999` returns 86, which matches the 84 you received.

However... the prediction in the app breaks, because it assums the highest possible value would be 83.
![image](https://user-images.githubusercontent.com/6956413/79249283-a5a1b100-7e42-11ea-8640-1358f94fdcec.png)

@mikebryant can you or someone else who knows the algorithm really well check my math here?

**Comment by mikebryant** [comment]
The difference is that the algorithm considers intermediate prices.

On Monday PM, we know the value is 86. This means that we can compute the internal rate value that should have been in effect - the code calculates that as min: 0.833333... and max: 0.843137...

Then the max rate must decrease by a minimum of 0.03, so the new max rate is 0.813137
Which then results in 102*0.813137 = 82.94, so the max predicted value for the next day is 83

**Comment by theRTC204** [comment]
I actually think the intermediate prices is the root cause of the issue. I've been running the numbers on this quite a bit in a C++ playground, to see how things come out.

```
Period     | Price | Rate     | Notes
-------------------------------------
Monday  AM | 92    | 0.900000 | Max
Monday  PM | 89    | 0.870000 | Max
Tuesday AM | 89    | 0.840000 | Max
Tuesday PM | 86    | 0.810000 | Max



Period     | Price | Rate     | Notes
-------------------------------------
Monday  AM | 91    |          | Actual

Monday  AM | 91    | 0.892157 | Reversed High
Monday  PM | 88    | 0.862157 | Predicted
Tuesday AM | 85    | 0.832157 | Predicted
Tuesday PM | 82    | 0.802157 | Predicted

Monday  AM | 91    | 0.882353 | Reversed Low
Monday  PM | 87    | 0.852353 | Predicted
Tuesday AM | 84    | 0.822353 | Predicted
Tuesday PM | 81    | 0.792353 | Predicted



Period     | Price | Rate     | Notes
-------------------------------------
Monday  PM | 86    |          | Actual

Monday  PM | 86    | 0.843137 | Reversed High
Tuesday AM | 83    | 0.813137 | Predicted
Tuesday PM | 80    | 0.783137 | Predicted

Monday  PM | 86    | 0.833333 | Reversed Low
Tuesday AM | 82    | 0.803333 | Predicted
Tuesday PM | 79    | 0.773333 | Predicted

```

In the first table, I start with the theoretical maximum values based on the buy price multiplied by the absolute best possible RNG rate for the pattern.

Then, in the next table, I use the reverse calculate the actual price, to get a high & low rate from Monday AM's 91 value and do the same calculations. Finally, in the third table, I do this again but with the Monday PM's 86 value.

Notice that with each iteration the potential high range is getting smaller and smaller. This is a problem, because it assumes the game is calculating these values every day again based on the last period price, when in actuality all the sell prices are pre-calculated based on the initial rate.

**Comment by mikebryant** [comment]
But isn't that exactly what we should expect?
If the RNG gave you a rate that only resulted in 91 on Monday AM, that means we can deduce that the rate on Monday was in fact, not the best possible. And as the rate is guaranteed to decrease by 0.03 each day, that means all of the following days are also guaranteed not to be the maximum possible

**Comment by theRTC204** [comment]
After debating it in Discord last night, and sleeping on it, I do now see what I was missing. You're right, the actual rate would not be best possible.

So we are back to square one with no leads as to what is causing all these reporting prediction errors. 😩
