### ISSUE TITLE
Guaranteed Min 999. Potential Max 0.

### ISSUE THREAD

**Issue by broncoempire** [mikebryant/ac-nh-turnip-prices#74]
Hi. 

When entering the following values, I am getting my results as guaranteed Min 999 and potential Max as 0.

First time: No
Pattern: Decreasing
Buy Price: 101
Monday: 89AM - 77PM

When clearing the Buy Price it readjusts to Guaranteed  min 89 and Potential max 139.

Any ideas why it’s not calculating correctly when I enter my buy price?

**Comment by ZZZZzzzzac** [comment]
a common rounding issue, i think it's the same problem like #47 #40, and i personally also had similiar experience, the boundary calculation may have `1` error

**Comment by broncoempire** [comment]
> a common rounding issue, i think it's the same problem like #47 #40, and i personally also had similiar experience, the boundary calculation may have `1` error

Thank you for pointing me to these other related issues :-D

**Comment by mikebryant** [comment]
The numbers you've put in aren't possible with the code retrieved from the game.

@broncoempire Are you confident this isn't the first week you've bought from daisy on your own island, and that the buy price is for your own island?
What are your prices for Tuesday AM/PM?

**Comment by broncoempire** [comment]
> The numbers you've put in aren't possible with the code retrieved from the game.
> 
> 
> 
> @broncoempire Are you confident this isn't the first week you've bought from daisy on your own island, and that the buy price is for your own island?
> 
> What are your prices for Tuesday AM/PM?

Thanks for the feedback @mikebryant. 
I have been keeping track of these in a spreadsheet for over a week now. 

Tuesday’s prices are: 
72 AM
68 PM

Thank you

**Comment by tsaiDavid** [comment]
@mikebryant - what if you purchased turnips on a friend's island but you've been keeping track of prices in your own? I'm getting this same behavior

**Comment by theRTC204** [comment]
Where you buy from makes no difference as long every value you enter into this tool is from **your island only**.

**Comment by peachiepie** [comment]
I am also having this issue. I purchased turnips on my own island for 101. this is my second time buying, but I'm not sure what my pattern was last week. Prices were 128 Monday AM, unknown Monday PM, 88 today AM, and 124 today PM.

**Comment by dotkupo** [comment]
Hi, i'm also having this issue too. I am not a first time buyer, and the site was working fine for me until this morning at which point it refuses to accept my Monday PM price.
Prices are as follows.

Sunday - 95

Monday 
AM - 85
**PM- 79** 

Tuesday
AM - 76
PM - 71

Wednesday
AM - 68
PM - 64

As mentioned at the top of the post, the site accepted the Monday PM price until this morning.
I even have a picture of the Monday PM price being accepted if that helps.
![stalnks](https://user-images.githubusercontent.com/63718470/79331390-f7197100-7f12-11ea-8387-99000f03895c.png)


However now when I put 79 into the PM price, I get the all patterns 999 min potential max 0 issue.
![image](https://user-images.githubusercontent.com/63718470/79331614-5e372580-7f13-11ea-89f6-11d16b8193e9.png)


This does work if I put 80 into the list instead of 79.
![image](https://user-images.githubusercontent.com/63718470/79331547-3942b280-7f13-11ea-8771-ebc2fee0a30d.png)

But well, 80 isn't what I got. I got 79.

**Comment by mikebryant** [comment]
@dotkupo Thanks for the details. I'll try and figure out why your numbers aren't matching the reverse-engineered code

**Comment by mikebryant** [comment]
The problem here is, the change in rate between 85 and 79 is too large. 
The minimum the internal rate value could be for 85 is 0.8842106316 - then 0.8842106316*95 == 84.000010002 - intceil gives 85

Maximum possible rate for 79 is 0.8315790526, *95 == 79.000009997 - ok, that's a little off, so should be even smaller. The difference between those two rates is 0.05263157895 - but all of the patterns in Treeki's code decrease by at most 0.05 in the rate.
