### ISSUE TITLE
Spreadsheet not loading for some reason?

### ISSUE THREAD

**Issue by jeffreyshao** [mikebryant/ac-nh-turnip-prices#86]
Opening the app in Chrome on Mac OS. For some reason when I enter the values, the spreadsheet isn't showing up? It works on Incognito for some reason though. Here's the error that's logged in the console when I run the page.

<img width="1392" alt="Screen Shot 2020-04-13 at 10 25 51 PM" src="https://user-images.githubusercontent.com/16729028/79179509-c7188380-7dd5-11ea-83e4-0c794976b395.png">

**Comment by theRTC204** [comment]
The error your receiving is because your browser has rejected the download of jQuery, which is required for the website to load correctly. You can see in the console you're receiving an ERR_CERT_COMMON_NAME_INVALID error, however there is nothing wrong with the certificate, so it's likely a client side issue.

You're on a critically out of date version of Chrome for macOS (as evidenced by the red update error in place of the menu button). I would start by updating your browser.

**Comment by mikebryant** [comment]
I'm afraid this is nothing to do with the code on our end, so I'm going to have to close this.
