### ISSUE TITLE
Why floor()?

### ISSUE THREAD

**Issue by ZZZZzzzzac** [mikebryant/ac-nh-turnip-prices#87]
https://github.com/mikebryant/ac-nh-turnip-prices/blob/42c3fdd2a38c020991e65f11d400767bbe4903be/js/predictions.js#L101

Is this and many other floor() on purpose?
This is mentioned in #47, and here are many invalid prediction issue(#82 #74 #60 #40) I think may relate to this

**Comment by theRTC204** [comment]
`Math.floor()` is used here because we want to convert the floating point number to it's whole number, but we do not want the number to round up.

**Comment by peter50216** [comment]
The original reversed code use intceil() in this place, so we _should_ be fine with using ceil() here too, and the current code is actually having a somehow wider range here.

The problem is that even when we're using a **wider** range we still get many invalid prediction issues... Changing this to Math.ceil would only makes the range smaller and won't turn any invalid pattern into valid one iiuc?

(Also no I don't think that's a difference between C++ and JS floating numbers, these numbers are small enough that the calculations should not have different result...)

**Comment by theRTC204** [comment]
`intceil` is not a feature of C++, so that's not actually true.

If you look at the implementation of `intceil` in the extracted code, you'll see that they are taking the float valve, adding `0.99999f` and then casting that to an integer.

In C++ casting to an integer results in _truncating_ the value, not rounding it. So, really, both `Math.floor()` and `Math.ceil()` are incorrect here.

We might be able to address some of the off-by-one issues if we reimplemented using `Math.trunc`. I have a work in progress for that, but it requires further testing...

**Comment by ZZZZzzzzac** [comment]
> intceil is not a feature of C++, so that's not actually true.
I'm simulating these function, randint(), randfloat() and intceil(), all perform just like what they should be (intceil() surely has little difference if` float f + 0.99999f `still less than `ceil(f)`, but that is trivial)

So according to C++ code , it shouldn't have so many issues about boundary point. Can we assume it is because the NS actually run code differently with our PC?

**Comment by theRTC204** [comment]
It's certainly possible that they have different floating point calculations, given the Switch is ARM based, while our PC are not...

**Comment by mikebryant** [comment]
Currently the prediction is wider than the reversed code might strictly allow - yet, we have reports from people with values that simply aren't possible with the reversed code - so staying strict to it doesn't exactly help...

**Comment by mikebryant** [comment]
We changed this from floor, thanks for raising this :)
